[package]
name = "toy"
version = "0.4.0"
authors = ["Patrick Monaghan <0x5f.manpat@gmail.com>"]
edition = "2021"

[dependencies]
common = { git = "https://github.com/manpat/common-rs.git" }
anyhow = "1.0"
